### ISSUE TITLE
Failed to open dynamic library 'nvcuda.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by guidorugo** [choderalab/coronavirus#13]
I'm not sure if I have to make this issue here or not.

Hardware:
I9 9900KF @ 5.1
AMD RX 5700 XT 50th Anniversary

After start, client 'System Info' got the error in title.

```18:16:28:Saving configuration to config.xml
18:16:28:<config>
18:16:28:  <!-- Network -->
18:16:28:  <proxy v=':8080'/>
18:16:28:
18:16:28:  <!-- Slot Control -->
18:16:28:  <power v='FULL'/>
18:16:28:
18:16:28:  <!-- User Information -->
18:16:28:  <user v='GuiroR'/>
18:16:28:
18:16:28:  <!-- Folding Slots -->
18:16:28:  <slot id='1' type='GPU'/>
18:16:28:</config>
18:16:28:WU00:FS00:Slot ID 0 no longer exists and not yet downloaded, dumping
18:16:28:WU00:FS00:Cleaning up
18:16:52:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
18:17:01:Saving configuration to config.xml
18:17:01:<config>
18:17:01:  <!-- Network -->
18:17:01:  <proxy v=':8080'/>
18:17:01:
18:17:01:  <!-- Slot Control -->
18:17:01:  <power v='FULL'/>
18:17:01:
18:17:01:  <!-- User Information -->
18:17:01:  <user v='GuiroR'/>
18:17:01:
18:17:01:  <!-- Folding Slots -->
18:17:01:  <slot id='1' type='GPU'/>
18:17:01:</config>
18:17:08:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
18:18:14:WU01:FS01:Connecting to 65.254.110.245:8080
18:18:14:WARNING:WU01:FS01:Failed to get assignment from '65.254.110.245:8080': No WUs available for this configuration
18:18:14:WU01:FS01:Connecting to 18.218.241.186:80
18:18:15:WARNING:WU01:FS01:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
18:18:15:ERROR:WU01:FS01:Exception: Could not get an assignment
```

![image](https://user-images.githubusercontent.com/1023222/76688050-35c0c080-6621-11ea-8950-9becfc965ef1.png)

**Comment by jchodera** [comment]
We ran out of WUs earlier today due to way more donor than we had anticipated signing up! We've added more COVID-19 WUs---can you try again?

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!

**Comment by dxf** [comment]
FYI - OP you have an AMD GPU and are attempting to use CUDA, which only runs on AMD. Don't panic!

**Comment by guidorugo** [comment]
I was not talking about the "lack of work", I was talking about the error message in the screen related to nvcuda.dll.

> Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?
> 
> Thanks so much for understanding, and thanks for helping us out!

Ok, I'll create a ticket there.



> FYI - OP you have an AMD GPU and are attempting to use CUDA, which only runs on AMD. Don't panic!

I think you mean CUDA is only for NVIDIA GPUs.

**Comment by dxf** [comment]
Oops.
