### ISSUE TITLE
Error 10053

### ISSUE THREAD

**Issue by jensJJ** [choderalab/coronavirus#14]
ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.

How can I fix this?

Thanks

**Comment by akod1ng** [comment]
same here:
`22:05:47:  
22:05:47:  <slot id='0' type='CPU'/>
22:05:47:  <slot id='1' type='GPU'/>
22:05:47:</config>
22:05:55:203:127.0.0.1:New Web connection
22:06:20:WU02:FS00:Connecting to 65.254.110.245:8080
22:06:21:WARNING:WU02:FS00:Failed to get assignment from '65.254.110.245:8080': No WUs available for this configuration
22:06:21:WU02:FS00:Connecting to 18.218.241.186:80
22:06:21:WARNING:WU02:FS00:Failed to get assignment from '18.218.241.186:80': No WUs available for this configuration
22:06:21:ERROR:WU02:FS00:Exception: Could not get an assignment
22:08:58:WU02:FS00:Connecting to 65.254.110.245:8080
22:08:58:WU02:FS00:Assigned to work server 155.247.164.213
22:08:58:WU02:FS00:Requesting new work unit for slot 00: READY cpu:11 from 155.247.164.213
22:08:58:WU02:FS00:Connecting to 155.247.164.213:8080
22:08:58:ERROR:WU02:FS00:Exception: Server did not assign work unit
`

**Comment by jchodera** [comment]
The `No WUs available for this configuration` may have been due to us running out of WUs earlier today. Can you check again?

**Comment by jensJJ** [comment]
Same error:

13:37:03:WU01:FS01:Assigned to work server 140.163.4.241
13:37:03:WU01:FS01:Requesting new work unit for slot 01: READY gpu:0:GP107 [GeForce GTX 1050 Ti]  2138 from 140.163.4.241
13:37:03:WU01:FS01:Connecting to 140.163.4.241:8080
13:37:19:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
13:37:35:ERROR:Receive error: 10053: An established connection was aborted by the software in your host machine.
13:37:37:ERROR:WU01:FS01:Exception: 10002: Received short response, expected 512 bytes, got 0

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!
