### ISSUE TITLE
[Setup] Can't connet to web control panel.

### ISSUE THREAD

**Issue by tobknight** [choderalab/coronavirus#15]
Hi,

I ran  folding@home client locally and tried to open the WebUI. but it keeping timeout.

I did not see anywhere mention this issue, so asking here.

![image](https://user-images.githubusercontent.com/27873598/76692368-ee8bfd00-662b-11ea-83dc-3cd1a67d7435.png)

Did I just run the demo?

**Comment by ChriStef** [comment]
I think the gui demo is not working properly, has not any info and to mine.

You seems to be folding OK and running. 

The web control gui on my chrome after a while it's not working. Try using over ignition mode private mode or Firefox. 

Also they mention that their end has too many requests from volunteers and trying to fix it. Maybe the stats won't work for now but the folding works OK. Choose any disease and if there is a work for cov it could use your folding power. Keep up...

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!

**Comment by tobknight** [comment]
Sure. Issue solve now.

I thought the web control panel using the local host so that made me think I may not set up correctly
