### ISSUE TITLE
I picked "any" and was sent to fold Alzheimers

### ISSUE THREAD

**Issue by masterrite** [choderalab/coronavirus#16]
How do I choose a specific project?

**Comment by akod1ng** [comment]
my first one was also a different project. at the moment its one on the coronavirus.

**Comment by jchodera** [comment]
Demand from all of you awesome donors was so high, we ran out of COVID-19 WUs earlier today! We have been working hard all weekend to set up more COVID-19 WUs---should be many more available now.

Thanks so much for all your support!

**Comment by jchodera** [comment]
We've now added an option for this! See https://foldingathome.org/2020/04/17/new-foldinghome-software-with-the-option-to-prioritize-covid-19-projects/
