### ISSUE TITLE
Coronavirus missing

### ISSUE THREAD

**Issue by Michal-Mikolas** [choderalab/coronavirus#18]
I can't see "Coronavirus" in the select menu. There is only "Any desease", "Alzheimer", "Huntington", "Cancer" and "Parkinson". 

I am sorry, but in the current situation I want to share my PC power **ONLY** for Coronavirus.

**Comment by dimon222** [comment]
There's no category for it (yet?)
Its part of pool "Any disease" currently.

**Comment by Michal-Mikolas** [comment]
So shouldn't the category be rather called "_Other diseases_" then "_Any disease_" ?

**Comment by dimon222** [comment]
I might assume its placeholder to make sure compute power is spent at anything available in F@H.
They did mention that new client is being worked on. Perhaps it might be there, as currently categories are hardcoded.

Here's FAQ about COVID specifically btw
https://foldingforum.org/viewtopic.php?f=24&t=32463

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!

**Comment by jchodera** [comment]
We've now added an option for this! See https://foldingathome.org/2020/04/17/new-foldinghome-software-with-the-option-to-prioritize-covid-19-projects/
