### ISSUE TITLE
No WUs available for this configuration

### ISSUE THREAD

**Issue by boeckie-xenopz** [choderalab/coronavirus#19]
Dear,

  How do I debug

`No WUs available for this configuration`

Thanks,
Bart

*********************** Log Started 2020-03-15T17:52:14Z ***********************
17:52:14:************************* Folding@home Client *************************
17:52:14:        Website: https://foldingathome.org/
17:52:14:      Copyright: (c) 2009-2018 foldingathome.org
17:52:14:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
17:52:14:           Args: --child --lifeline 2731 /etc/fahclient/config.xml --run-as
17:52:14:                 fahclient --pid-file=/var/run/fahclient.pid --daemon
17:52:14:         Config: /etc/fahclient/config.xml
17:52:14:******************************** Build ********************************
17:52:14:        Version: 7.5.1
17:52:14:           Date: May 11 2018
17:52:14:           Time: 19:59:04
17:52:14:     Repository: Git
17:52:14:       Revision: 4705bf53c635f88b8fe85af7675557e15d491ff0
17:52:14:         Branch: master
17:52:14:       Compiler: GNU 6.3.0 20170516
17:52:14:        Options: -std=gnu++98 -O3 -funroll-loops
17:52:14:       Platform: linux2 4.14.0-3-amd64
17:52:14:           Bits: 64
17:52:14:           Mode: Release
17:52:14:******************************* System ********************************
17:52:14:            CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
17:52:14:         CPU ID: GenuineIntel Family 6 Model 158 Stepping 9
17:52:14:           CPUs: 8
17:52:14:         Memory: 15.57GiB
17:52:14:    Free Memory: 14.52GiB
17:52:14:        Threads: POSIX_THREADS
17:52:14:     OS Version: 4.10
17:52:14:    Has Battery: false
17:52:14:     On Battery: false
17:52:14:     UTC Offset: 1
17:52:14:            PID: 2733
17:52:14:            CWD: /var/lib/fahclient
17:52:14:             OS: Linux 4.10.0-40-generic x86_64
17:52:14:        OS Arch: AMD64
17:52:14:           GPUs: 1
17:52:14:          GPU 0: Bus:1 Slot:0 Func:0 NVIDIA:8 GP102 [GeForce GTX 1080 Ti] 11380
17:52:14:  CUDA Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:6.1 Driver:10.0
17:52:14:OpenCL Device 0: Platform:0 Device:0 Bus:1 Slot:0 Compute:1.2 Driver:410.78
17:52:14:***********************************************************************

**Comment by dimon222** [comment]
Servers are out of WU very fast due to very huge cluster of users, so its actually expected behaviour (everyone is panicking and donating power in hope to end current nightmares with COVID-19). It basically means there's nothing to assign to you to work with.

You might have to wait couple of hours until owners of projects upload new WUs to work with.

**Comment by boeckie-xenopz** [comment]
thx for the feedback!
