### ISSUE TITLE
Can't install folding@home on new ubuntu version (19.10)

### ISSUE THREAD

**Issue by boulabiar** [choderalab/coronavirus#20]
I am getting dependency problems for gtk (python) when trying to install this project.
Can you update the install instruction page and the packages so they can be installed without problems?

Is there a way to launch the project without a graphical interface if it is a problem?
(Need instructions for this as I am new to the project.)

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!
