### ISSUE TITLE
How do I know i am folding for COVID-19?

### ISSUE THREAD

**Issue by amalic** [choderalab/coronavirus#23]
Your blog post is saying COVID-19 has highest priority, but how can I be for sure that my computer is not working on something else?

**Comment by Allu2** [comment]
I'm guessing here but one indication might be having `FaHCore_22.exe` running as blog post mentions it 🤔
> All projects are using the new GPU-accelerated Core22 based on the open source OpenMM biomolecular simulation engine.

What I'd really like to see however is option for exclusively supporting this, as other such options exist already:
![image](https://user-images.githubusercontent.com/644641/76748905-4178c800-6784-11ea-8957-4dfc3d8df7e6.png)

**Comment by amalic** [comment]
Thanks for the reply. Got the webview now working which actually shows the project it's working on. 

I am running it via NVidia docker:
https://hub.docker.com/r/amalic/nvdocker-folding-home/

Feel free to add it as alternative way of running Folding@Home to your blogpost and social media publications for folks like me who don't want to install additional software if not necessary.

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added new info on where to submit questions/issues like this. Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!

**Comment by jchodera** [comment]
We've now added an option for this! See https://foldingathome.org/2020/04/17/new-foldinghome-software-with-the-option-to-prioritize-covid-19-projects/
