### ISSUE TITLE
"Any disease" option does not contribute to COVID-19

### ISSUE THREAD

**Issue by touloumtzidis** [choderalab/coronavirus#27]
I am running Ubuntu 18.04 (cli), is there any option I can add to the config.xml file to manually contribute to the project's ID?

**Comment by lolmaus** [comment]
Same here on Windows 10.

How do I select coronavirus specifically?

**Comment by dimon222** [comment]
https://foldingforum.org/viewtopic.php?f=24&t=32463

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you re-file your issues there?

Thanks so much for understanding, and thanks for helping us out!

**Comment by jchodera** [comment]
We've now added an option for this! See https://foldingathome.org/2020/04/17/new-foldinghome-software-with-the-option-to-prioritize-covid-19-projects/
