### ISSUE TITLE
Provide docker support

### ISSUE THREAD

**Issue by pmoranga** [choderalab/coronavirus#28]
Nowadays any application should be shipped as an option to run containerised. It would be easier for many user to have available a docker pre-build image from FAH, with multiple exemples of executing the container, using GPU and CPU.

Examples of configuration should also contain explicit configuration for researching COVID-19 specifically.

**Comment by amalic** [comment]
I created an image: https://hub.docker.com/r/amalic/nvdocker-folding-home a couple of days ago

@FAH_team: Please feel free to link to the Docker image on your website and social media channels.

@pmoranga: Please leave this ticket open so devs can see my comment.

**Comment by jchodera** [comment]
@amalic: Thanks so much!

@Antonthynell : Can you get this info onto the "Download" page?

**Comment by Antonthynell** [comment]
@jchodera Social media, check. Website soon done

**Comment by amalic** [comment]
Shared by NVidia

https://www.linkedin.com/posts/kingmesal_docker-hub-activity-6646752145909575680-xnqn

**Comment by lukasheinrich** [comment]
we at @CERN (meaning @rochaporto)  also set up a Helm Chart to run F@H ono k8s clusters

https://github.com/rochaporto/helm-foldingathome

**Comment by amalic** [comment]
> we at @CERN (meaning @rochaporto) also set up a Helm Chart to run F@H ono k8s clusters
> 
> https://github.com/rochaporto/helm-foldingathome

Can I share it on Linkedin?

**Comment by lukasheinrich** [comment]
of course!

**Comment by amalic** [comment]
> of course!

Done! Almost forgot to provide a link.

https://www.linkedin.com/posts/alexandermalic_2019ncov-covid19-coronavirus-activity-6647428399205883904-GBTd

**Comment by pmoranga** [comment]
Great to see such nice contributions!
@amalic just a note, the link, on the linked in post, for docker hub is wrong, it's as you copied the link when you are logged in, the correct link is: https://hub.docker.com/r/amalic/nvdocker-folding-home

Can you guys open a PR for adding the references to yours contribution in this main repository ?

**Comment by jchodera** [comment]
We now have an official docker image too!
https://hub.docker.com/r/foldingathome/fah-gpu
