### ISSUE TITLE
Question: Is cpu-only client usable for coronavirus research? 

### ISSUE THREAD

**Issue by ptrm** [choderalab/coronavirus#29]
I could not find any specific information how much non-gpu machines can be used for this specific project. In README thet's only "We're especially in need of more donors with GPUs to help out", which does not tell about how much non-gpu machines can help. I have a i7 laptop with intel uhd and radeon 530 with seemingly no support for OpenCL, at least F@H-wise, but then the cpu is still of some use.

As this is an issue, the expectation is a slight readme update.

**Comment by dimon222** [comment]
Yes, there are few CPU COVID-19 projects too
https://foldingforum.org/viewtopic.php?f=24&t=32463

**Comment by amalic** [comment]
Cool. Added a ENV switch to my docker image. Should show in a couple of minutes.
see: https://hub.docker.com/r/amalic/nvdocker-folding-home

**Comment by rjfnobre** [comment]
The radeon 530 GPU has OpenCL support and should be supported by Folding@Home.
Maybe reinstall the display drivers from AMD's website?

https://www.amd.com/en/support/graphics/radeon-500-series/radeon-500-series/radeon-530

**Comment by ptrm** [comment]
I indeed managed to install amd pro drivers for opencl, and blacktable RAW photo editor makes use of these extensions (both my intel uhd and radeon cards). clinfo also show the card since the drivers were installed.

Anyway, Radeon 350 (Iceland) is a mobile graphics card, and I noticed a 10-20% improvement when benching it against cpu in blacktable-cli (https://math.dartmouth.edu/~sarunas/darktable_bench.html - here the improvements are huge), so nothing drastic. So I guess it's not whitelisted, at least as far as I googled ;)

**Comment by ptrm** [comment]
~~EDIT `<gpu v='false'/>` seems to make ignore GPUs altogether, changing the value to true fixed it.~~  - that was premature

This might get offtopic, but actually, running FAHClient as my own user I did get my radeon recognised (more or less properly):

```
 ~ $ FAHClient --child /etc/fahclient/config.xml
15:59:44:INFO(1):Read GPUs.txt
15:59:45:************************* Folding@home Client *************************
15:59:45:        Website: https://foldingathome.org/
15:59:45:      Copyright: (c) 2009-2018 foldingathome.org
15:59:45:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
15:59:45:           Args: --child /etc/fahclient/config.xml
15:59:45:         Config: /etc/fahclient/config.xml
15:59:45:******************************** Build ********************************
15:59:45:        Version: 7.5.1
15:59:45:           Date: May 11 2018
15:59:45:           Time: 19:59:04
15:59:45:     Repository: Git
15:59:45:       Revision: 4705bf53c635f88b8fe85af7675557e15d491ff0
15:59:45:         Branch: master
15:59:45:       Compiler: GNU 6.3.0 20170516
15:59:45:        Options: -std=gnu++98 -O3 -funroll-loops
15:59:45:       Platform: linux2 4.14.0-3-amd64
15:59:45:           Bits: 64
15:59:45:           Mode: Release
15:59:45:******************************* System ********************************
15:59:45:            CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
15:59:45:         CPU ID: GenuineIntel Family 6 Model 142 Stepping 10
15:59:45:           CPUs: 8
15:59:45:         Memory: 15.54GiB
15:59:45:    Free Memory: 9.61GiB
15:59:45:        Threads: POSIX_THREADS
15:59:45:     OS Version: 5.3
15:59:45:    Has Battery: true
15:59:45:     On Battery: false
15:59:45:     UTC Offset: 1
15:59:45:            PID: 9527
15:59:45:            CWD: /home/piotr
15:59:45:             OS: Linux 5.3.0-42-generic x86_64
15:59:45:        OS Arch: AMD64
15:59:45:           GPUs: 1
15:59:45:          GPU 0: Bus:1 Slot:0 Func:0 AMD:5 Mars [Radeon R7 M260/M265/M270]
15:59:45:           CUDA: Not detected: Failed to open dynamic library 'libcuda.so':
15:59:45:                 libcuda.so: cannot open shared object file: No such file or
15:59:45:                 directory
15:59:45:OpenCL Device 0: Platform:0 Device:0 Bus:NA Slot:NA Compute:2.0 Driver:1.3
15:59:45:OpenCL Device 1: Platform:1 Device:0 Bus:NA Slot:NA Compute:2.1 Driver:1.0
15:59:45:OpenCL Device 2: Platform:2 Device:0 Bus:1 Slot:0 Compute:1.2 Driver:2841.17
15:59:45:***********************************************************************
15:59:45:<config>
15:59:45:  <!-- Client Control -->
15:59:45:  <fold-anon v='true'/>
15:59:45:
15:59:45:  <!-- Folding Slot Configuration -->
15:59:45:  <gpu v='false'/>
15:59:45:
15:59:45:  <!-- Network -->
15:59:45:  <proxy v=':8080'/>
15:59:45:
15:59:45:  <!-- Slot Control -->
15:59:45:  <power v='full'/>
15:59:45:
15:59:45:  <!-- User Information -->
15:59:45:  <passkey v='********************************'/>
15:59:45:  <user v='ptrm'/>
15:59:45:
15:59:45:  <!-- Folding Slots -->
15:59:45:  <slot id='0' type='CPU'/>
15:59:45:  <slot id='18446744073709551615' type='GPU'/>
15:59:45:</config>
15:59:45:Trying to access database...
15:59:45:Successfully acquired database lock
15:59:45:Enabled folding slot 00: READY cpu:7
15:59:45:Enabled folding slot -1: READY gpu:0:Mars [Radeon R7 M260/M265/M270]
15:59:45:WU00:FS00:Connecting to 65.254.110.245:8080
15:59:45:WU01:FS4294967295:Connecting to 65.254.110.245:8080
```

I just wonder what is missing to be working as use `fahclient`:
```
 ~ $ groups
piotr adm tty uucp dialout cdrom sudo audio dip video plugdev lpadmin sambashare vboxusers docker render
 ~ $ groups fahclient
fahclient : nogroup video render
```

**Comment by jchodera** [comment]
Hi folks! We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). Could you migrate the discussion there?

Thanks so much for understanding, and thanks for helping us out!
