### ISSUE TITLE
[Question] CPU project running on GPU?

### ISSUE THREAD

**Issue by nref-dan** [choderalab/coronavirus#30]
Hi team,
I've just noticed that my GPU seems to be running something you've described as a CPU project. Is this intended?
Screenshot from web control below

![Screenshot from 2020-03-17 12-41-18](https://user-images.githubusercontent.com/3584566/76857344-2c1ba080-684d-11ea-9932-fea0f2a7f184.png)

**Comment by tutacat** [comment]
Folding@home uses both cpu and gpu, please remember to keep the issues channel open for researchers

**Comment by nref-dan** [comment]
> 
> 
> Folding@home uses both cpu and gpu, please remember to keep the issues channel open for researchers

Yes, it's just that your project is marked

> ` **CPU**`

 so it seemed important, I don't create WUs so I didn't know if it was possible to accidentally set something incorrectly. Just wanted to ensure you're getting the right results.
