### ISSUE TITLE
502 Bad Gateway in Stats API

### ISSUE THREAD

**Issue by lucidyan** [choderalab/coronavirus#33]
Maybe this repository not the right place for such kinds of issues, but your stats API return '502 Bad Gateway' for all endpoints:
https://stats.foldingathome.org/api

**Comment by AndresLuga** [comment]
Bad Gateway here:
https://stats.foldingathome.org/os

**Comment by jchodera** [comment]
Our poor server is being hammered right now, but we're actively working on getting new static pages (updated hourly) up for current stats. Thanks for bearing with us.

For future: We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've just added [new info on where to submit questions/issues like this](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#questions-or-feedback-about-running-foldinghome). 

Thanks so much for understanding, and thanks for helping us out!
