### ISSUE TITLE
Unclear how to contribute

### ISSUE THREAD

**Issue by erdebee** [choderalab/coronavirus#5]
Hello, can you please share with us how we can configure FAH Client to help with the Corona project?

**Comment by goncaloperes** [comment]
Me and the rest of the team [Volunteer Computing Portugal](https://www.linkedin.com/company/volunteercomputing/) are facing the same problem @rbrondgeest 
Already Tweeted Greg Bowman in different threads as well:
1) [Thread 1](https://twitter.com/GoncaloMPeres/status/1238023951965720576)
2) [Thread 2](https://twitter.com/drGregBowman/status/1237843192063463433)

**Comment by marvin-zander** [comment]
Hello,

you just have to select "any disease" to contribute to the corona projects!

https://foldingathome.org/2020/02/27/foldinghome-takes-up-the-fight-against-covid-19-2019-ncov/

Best regards

**Comment by erdebee** [comment]
For now only GPU contributes to the Corona project. Seemingly they are working on CPU based jobs, but no information on when this will be available.

**Comment by erdebee** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">CPU-based <a href="https://twitter.com/hashtag/coronavirus?src=hash&amp;ref_src=twsrc%5Etfw">#coronavirus</a> jobs are coming to <a href="https://twitter.com/foldingathome?ref_src=twsrc%5Etfw">@foldingathome</a> ASAP!</p>&mdash; Greg Bowman (@drGregBowman) <a href="https://twitter.com/drGregBowman/status/1237843192063463433?ref_src=twsrc%5Etfw">March 11, 2020</a></blockquote>

**Comment by rafwiewiora** [comment]
Hi folks, on the GPU side we are making sure on our side that all of F@h will be running coronavirus only -- there is nothing you have to do, just let it run. Thanks to everyone for your contributions, this is amazing!

**Comment by jchodera** [comment]
Thanks for the great feedback, all! I've updated the README with a [How to contribute](https://github.com/FoldingAtHome/coronavirus/blob/master/README.md#how-to-contribute) section!
