### ISSUE TITLE
HTTP_REQUEST_ENTITY_TOO_LARGE

### ISSUE THREAD

**Issue by bartengine27** [choderalab/coronavirus#50]
Dear,

  At the end of an upload, I get

`09:32:55:WU01:FS01:Upload 95.27%
09:33:01:WU01:FS01:Upload 97.19%
09:33:04:WU00:FS00:0xa7:Completed 117500 out of 125000 steps (94%)
09:33:05:WARNING:WU01:FS01:Exception: Failed to send results to work server: 10001: Server responded: HTTP_REQUEST_ENTITY_TOO_LARGE
`

Any idea how I can debug this?

Thanks,
Bart

**Comment by TheMythoclast** [comment]
Its trying to upload a file than the server will allow. You could try running the command locally and see what it generates to make sure its not generating output of ungodly size, though I've never heard of that happening. Probably just need to increase the maximum file size allowance in IIS/Apache etc.

**Comment by bartengine27** [comment]
`
FAHClient /etc/fahclient/config.xml --send
`
its output:
`10:52:50:Trying to access database...
10:52:51:Successfully acquired database lock
10:52:51:Enabled folding slot 00: READY cpu:47
10:52:51:Enabled folding slot 01: READY gpu:0:GV100GL [Tesla V100 PCIe 32GB]
10:52:51:WU03:FS01:Sending unit results: id:03 state:SEND error:NO_ERROR project:11759 run:0 clone:98 gen:13 core:0x22 unit:0x0000001380fccb0a5e6d7c7befeabd81
10:52:51:WU03:FS01:Uploading 49.92MiB to 128.252.203.10
10:52:51:WU03:FS01:Connecting to 192.168.7.139:8080
10:52:51:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:13860 run:0 clone:17908 gen:15 core:0xa7 unit:0x000000100d5a98395e730fbbc9d16ea5
10:52:51:WU00:FS00:Uploading 5.49MiB to 13.90.152.57
10:52:51:WU00:FS00:Connecting to 192.168.7.139:8080
10:52:51:WU01:FS01:Sending unit results: id:01 state:SEND error:NO_ERROR project:11758 run:0 clone:4092 gen:0 core:0x22 unit:0x000000009bf7a4d55e6d771b3cd854f7
10:52:51:WU01:FS01:Uploading 55.24MiB to 155.247.164.213
10:52:51:WU01:FS01:Connecting to 192.168.7.139:8080
10:52:52:WARNING:WU01:FS01:Exception: Failed to send results to work server: Transfer failed
10:52:52:WU01:FS01:Trying to send results to collection server
10:52:52:WU01:FS01:Uploading 55.24MiB to 155.247.164.214
10:52:52:WU01:FS01:Connecting to 192.168.7.139:8080
10:52:52:ERROR:WU01:FS01:Exception: Transfer failed
10:52:53:WU01:FS01:Sending unit results: id:01 state:SEND error:NO_ERROR project:11758 run:0 clone:4092 gen:0 core:0x22 unit:0x000000009bf7a4d55e6d771b3cd854f7
10:52:53:WU01:FS01:Uploading 55.24MiB to 155.247.164.213
10:52:53:WU01:FS01:Connecting to 192.168.7.139:8080
10:52:59:WU01:FS01:Upload 8.26%
10:53:05:WU01:FS01:Upload 11.88%
10:53:11:WU01:FS01:Upload 18.44%
10:53:14:WU03:FS01:Upload 2.25%
10:53:14:WARNING:WU03:FS01:Exception: Failed to send results to work server: Transfer failed
10:53:14:WU03:FS01:Trying to send results to collection server
10:53:15:WU00:FS00:Upload 21.64%
10:53:15:WU03:FS01:Uploading 49.92MiB to 155.247.166.219
10:53:15:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
10:53:15:WU03:FS01:Connecting to 192.168.7.139:8080
10:53:15:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:13860 run:0 clone:17908 gen:15 core:0xa7 unit:0x000000100d5a98395e730fbbc9d16ea5
10:53:15:WU00:FS00:Uploading 5.49MiB to 13.90.152.57
10:53:15:WU00:FS00:Connecting to 192.168.7.139:8080
10:53:17:WU01:FS01:Upload 24.89%
10:53:21:WU03:FS01:Upload 11.02%
10:53:23:WU01:FS01:Upload 29.76%
10:53:27:WU03:FS01:Upload 16.53%
10:53:29:WU01:FS01:Upload 33.38%
10:53:33:WU03:FS01:Upload 21.79%
10:53:35:WU01:FS01:Upload 38.70%
10:53:38:WU00:FS00:Upload 23.92%
10:53:38:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
10:53:39:WU03:FS01:Upload 27.42%
10:53:42:WU01:FS01:Upload 43.22%
10:53:45:WU03:FS01:Upload 34.31%
10:53:48:WU01:FS01:Upload 48.99%
10:53:51:WU03:FS01:Upload 42.69%
10:53:54:WU01:FS01:Upload 53.41%
10:53:57:WU03:FS01:Upload 50.96%
10:54:00:WU01:FS01:Upload 59.29%
10:54:03:WU03:FS01:Upload 56.59%
10:54:06:WU01:FS01:Upload 64.38%
10:54:09:WU03:FS01:Upload 60.72%
10:54:12:WU01:FS01:Upload 70.94%
10:54:15:WU00:FS00:Sending unit results: id:00 state:SEND error:NO_ERROR project:13860 run:0 clone:17908 gen:15 core:0xa7 unit:0x000000100d5a98395e730fbbc9d16ea5
10:54:15:WU00:FS00:Uploading 5.49MiB to 13.90.152.57
10:54:15:WU00:FS00:Connecting to 192.168.7.139:8080
10:54:16:WU03:FS01:Upload 70.61%
10:54:18:WU01:FS01:Upload 77.17%
10:54:22:WU03:FS01:Upload 78.50%
10:54:24:WU01:FS01:Upload 81.01%
10:54:28:WU03:FS01:Upload 87.52%
10:54:30:WU01:FS01:Upload 86.78%
10:54:34:WU03:FS01:Upload 93.78%
10:54:36:WU01:FS01:Upload 91.76%
10:54:38:WU00:FS00:Upload 22.78%
10:54:38:WARNING:WU00:FS00:Exception: Failed to send results to work server: Transfer failed
10:54:38:ERROR:WU03:FS01:Exception: 10001: Server responded: HTTP_REQUEST_ENTITY_TOO_LARGE
10:54:39:WU03:FS01:Sending unit results: id:03 state:SEND error:NO_ERROR project:11759 run:0 clone:98 gen:13 core:0x22 unit:0x0000001380fccb0a5e6d7c7befeabd81
10:54:39:WU03:FS01:Uploading 49.92MiB to 128.252.203.10
10:54:39:WU03:FS01:Connecting to 192.168.7.139:8080
10:54:42:WU01:FS01:Upload 96.18%
10:54:45:WARNING:WU01:FS01:Exception: Failed to send results to work server: 10001: Server responded: HTTP_REQUEST_ENTITY_TOO_LARGE
`

thanks,
Bart

**Comment by jchodera** [comment]
Hi folks!

We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've added [new info on where to submit questions/issues](https://github.com/foldingathome/coronavirus#questions-or-feedback-about-running-foldinghome) like this. Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!
