### ISSUE TITLE
Running on ssh server without gui.

### ISSUE THREAD

**Issue by siulkilulki** [choderalab/coronavirus#51]
I have a ssh only accessible computer with GPU card. Can I run your code there, without web client?

**Comment by jaimergp** [comment]
Yes! Check the docs [here](https://foldingathome.org/support/faq/installation-guides/linux/command-line-options/). The GUI is only a reporter; the calculation happens in a background process.

**Comment by jchodera** [comment]
Hi folks!

We're getting a huge influx of interest, and we need to keep this issue tracker clear for scientific discussions among labs working on COVID-19 targeting, so I've added [new info on where to submit questions/issues](https://github.com/foldingathome/coronavirus#questions-or-feedback-about-running-foldinghome) like this. Could you re-file your issue in the appropriate place?

Thanks so much for understanding, and thanks for helping us out!
