### ISSUE TITLE
please add FreeBSD support

### ISSUE THREAD

**Issue by dyeske** [choderalab/coronavirus#61]
After looking at the client it appears that FreeBSD could be supported.  The ctypes call could be changed to use something more portable or FreeBSD specific instead of prctl().  This could be made into a FreeBSD port.

**Comment by jchodera** [comment]
Good idea! Could you refile your feature request in the client issue tracker?
https://github.com/FoldingAtHome/fah-issues/issues

**Comment by dyeske** [comment]
https://github.com/FoldingAtHome/fah-issues/issues/1334
