### ISSUE TITLE
Use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [choderalab/coronavirus#62]
Please use https://foldingathome.org/ at the top of https://github.com/FoldingAtHome/coronavirus/ to save one request, and protect against certain attacks.

```
$ curl -I http://foldingathome.org
HTTP/1.1 301 Moved Permanently
Server: nginx/1.14.2
Date: Thu, 26 Mar 2020 07:57:21 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://foldingathome.org/

```

**Comment by EllieLockhart** [comment]
Has this documentation change been implemented yet? If not I would be happy to do so.

**Comment by paulmenzel** [comment]
No, looking at https://github.com/FoldingAtHome/coronavirus there is still just *foldingathome.org*:

    <a title="http://foldingathome.org" role="link" target="_blank" class="text-bold" rel="noopener noreferrer" href="http://foldingathome.org">foldingathome.org</a>

Only the “GitHub repository owner” can edit the project/repository metadata.

**Comment by PantherX** [comment]
I have reviewed the mentioned Pull Request but will inform someone who might be able to merge it 😄

**Comment by anand-bhat** [comment]
I believe @paulmenzel is referring to the link in the description of the repo, not in the README. The repo owner should be able to edit this from the Github UI.

![image](https://user-images.githubusercontent.com/7332442/92325040-b7eae880-f08a-11ea-8508-4a163f971bd6.png)

**Comment by jchodera** [comment]
Fixed, thanks!
