### ISSUE TITLE
GPU Work server down?

### ISSUE THREAD

**Issue by W944** [choderalab/coronavirus#8]
The web control panel indicates that my CPU is processing a job but the GPU section stays on the yellow circle.
The Advanced Control panel says the GPU status is Downloading, Project:0, Waiting on:WS Assignment, Work Server:140.163.4.241
This IP doesn't reply to pings.

Found the logs tab:
23:12:06:WARNING:WU01:FS01:WorkServer connection failed on port 8080 trying 80
23:12:06:WU01:FS01:Connecting to 140.163.4.241:80
23:12:27:ERROR:WU01:FS01:Exception: Failed to connect to 140.163.4.241:80: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by antont** [comment]
i started a GPU job a while ago but a bit earlier .. ah also found fahcontroller and the log now, am new here. seems to be the same ip that worked then, maybe down now:

22:54:34:WU01:FS01:Requesting new work unit for slot 01: READY gpu:0:GP104M [GeForce GTX 1070 Mobile] from 140.163.4.241
22:54:34:WU01:FS01:Connecting to 140.163.4.241:8080
22:54:34:WU00:FS00:Download complete
22:54:34:WU00:FS00:Received Unit: id:00 state:DOWNLOAD error:NO_ERROR project:14304 run:5 clone:142 gen:4 core:0xa7 unit:0x000000049bf7a4d55e66ca59844f6adb

UPDATE: oh now it replied, tried it in a browser window, and maybe for a minute it didn't reply but then that came, maybe works now:

![image](https://user-images.githubusercontent.com/201016/76669921-863f0c00-6596-11ea-856e-ed88109bd2fd.png)

**Comment by jchodera** [comment]
Hi folks! Our poor work servers are straining under the load from all of you amazing folks contributing your spare computing cycles. We're actively working to spin up more servers on our end to handle the load, but please bear with us---it may take another day or two before we can fully scale up to handle the load.
