### ISSUE TITLE
undefined name 'structure' In 6lu7_complex/edit_residues.py

### ISSUE THREAD

**Issue by cclauss** [choderalab/coronavirus#9]
flake8 testing of https://github.com/FoldingAtHome/coronavirus on Python 3.8.1

$ `time flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./system-preparation/6lu7_complex/edit_residues.py:66:33: F821 undefined name 'structure’
PDBFile.writeFile(new_topology, structure.positions, open("input/6lu7_renamed.pdb", "w"), keepIds=True)
                                ^
1     F821 undefined name 'structure'
1
```

**Comment by jchodera** [comment]
Thanks, but these scripts were written in a hurry, and not meant to be representative of best practices.

For more on our software best practices for open source tools we develop, see
http://github.com/choderalab/software-development

Contributions there are welcomed!
